### ISSUE TITLE
Option --file not working correctly

### ISSUE THREAD

**Issue by hfjn** [mtneug/texlive-docker#1]
Hey,

thanks for the awesome image.

Unfortunately I have a problem with the `file` option.

When referencing another file it isn't recognized and the script is just showing me the available options.

```
~/code/udp_seminar/presentation on master
$ docker run --rm -v $PWD mtneug/texlive --file=beamer -b -g -w
Unkown option '--file=beamer'

Usage: build.sh [OPTIONS]

Options:

  -f, --file=main       Name of the tex file without file ending
  -b, --bibtex          Run bibtex
  -g, --glossaries      Run makeglossaries
  -w, --watch           Watch for changes
      --ignore-errors   Continue watching even if an error occurred
  -h, --help            Print usage
```

Any idea what might be wrong?

**Comment by mtneug** [comment]
`--file` must be used without `=`, i.e. `--file beamer` instead of `--file=beamer`. The usage information should only indicate only the default. Admitting this is not the best way to communicating that. I will update the documentation.
